'use client';
import {useState} from 'react';
import InteractiveSpace from './interactive-space';
import {ArrowUpRight, ArrowDown, Moon, Sun, Code2, Sparkles} from 'lucide-react';
export default function Home(){
 const [light,setLight]=useState(false);
 return <div className={light?'site light':'site'}>
 <a className="skip" href="#works">跳至作品</a>
 <header><a className="brand" href="#home"><Sparkles size={23}/><span>Royal Milktea<span className="brand-sub">PIN HUNG LIN</span></span></a><nav><a href="#works">作品</a><a href="#about">關於</a><a href="#contact">聯絡 <ArrowUpRight size={14}/></a></nav><button className="theme" onClick={()=>setLight(!light)} aria-label={light?'切換星夜深色':'切換日光亮色'}>{light?<Moon size={17}/>:<Sun size={17}/>}<span>{light?'星夜':'日光'}</span></button></header>
 <main><section className="hero" id="home"><div className="hero-shade"/><InteractiveSpace light={light}/><div className="hero-copy"><p className="eyebrow">A LITTLE CURIOSITY. A LITTLE STARLIGHT.</p><h1>在星空下，<br/>把點子<span>釀成作品。</span></h1><p className="intro">嗨，我是林品宏，皇家奶茶大師。<br/>用 AI、自動化與一點遊戲精神，<br className="mobile-break"/>探索想法成真的各種可能。</p><a className="primary" href="#works">探索我的作品 <ArrowDown size={17}/></a><div className="hero-sign">林品宏 Pin Hung Lin <span>／ Royal Milktea Master</span></div></div><div className="hero-bottom"><span>AI BUILDER · AUTOMATION TINKERER · GAME CREATOR</span><a href="#works">SCROLL TO EXPLORE ↓</a></div></section>
 <section id="works" className="works wrap"><div className="section-head"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>正在沖泡的<span>小宇宙。</span></h2></div><a className="text-link" href="https://github.com/RoyalMilkteaMaster" target="_blank" rel="noreferrer">所有 GitHub 專案 <ArrowUpRight size={17}/></a></div><article className="featured"><div className="feature-copy"><span className="tag">MULTI-AGENT × MARKET RESEARCH</span><h3>Market Council</h3><p className="subtitle">七席 AI，把判斷攤開來討論。</p><p>市場辯論室讓不同專業的 AI 先獨立蒐證，再公開辯論與投票。保留證據來源、少數意見與研究紀錄，讓分析過程能被檢查。</p><p className="award">✧ 2026 雲湧智生黑客松 · 智慧交易冠軍</p><div className="feature-links"><a href="https://github.com/RoyalMilkteaMaster/AI-agnets-debating-chamber" target="_blank" rel="noreferrer">探索專案 <ArrowUpRight size={17}/></a><a href="https://www.youtube.com/watch?v=GzGIeinCTGY" target="_blank" rel="noreferrer">觀看 Demo <ArrowUpRight size={17}/></a></div></div><div className="workflow" aria-label="市場辯論室研究流程示意"><div className="window-bar"><i/><i/><i/><span>market council / research</span></div><div className="workflow-body"><small>SEVEN PERSPECTIVES. TRACEABLE EVIDENCE.</small><div className="flow-node"><span>01</span><div>獨立蒐證<small>Research independently</small></div><span>↗</span></div><div className="flow-line"/><div className="flow-node active"><span>02</span><div>交叉辯論<small>Exchange & challenge</small></div><Sparkles size={20}/></div><div className="flow-line"/><div className="flow-node"><span>03</span><div>留下判斷依據<small>Evidence, votes & report</small></div><span>✓</span></div><p>流程示意 · 保留共識，也保留分歧。</p></div></div></article>
 <div className="project-grid"><a className="project" href="https://www.youtube.com/watch?v=95etQyKrksA&t=44s" target="_blank" rel="noreferrer"><div className="project-num">02 <ArrowUpRight/></div><span className="tag">GENERATIVE AI × CREATIVE TOOLS</span><h3>CB 影像生成平台</h3><p>透過自然語言串起角色設定、Blender 場景、人物姿勢與 ComfyUI 合成，探索更穩定的角色與影像生成流程。</p><span className="project-foot">FastAPI · CLI Bridge · Blender · ComfyUI</span></a><a className="project" href="https://github.com/RoyalMilkteaMaster/milktea-agents-skills-for-claude" target="_blank" rel="noreferrer"><div className="project-num">03 <ArrowUpRight/></div><span className="tag">AI DEVELOPMENT × WORKFLOW</span><h3>奶茶流 Milktea Skills</h3><p>把需求釐清、實作與審查整理成可重用的繁體中文 AI 開發協作 Skills，讓每次創作都有方法可循。</p><span className="project-foot">Multi-Agent · Skills · Claude Code</span></a></div></section>
 <section id="about" className="about wrap"><div><p className="eyebrow">02 / BEHIND THE BREW</p><h2>一杯奶茶，<br/><span>很多好奇。</span></h2></div><div className="about-copy"><p>我是林品宏，畢業於成功大學光電科學與工程學系。從政策研究到製造現場的跨部門工作，我逐步把對問題的觀察，帶進 AI 應用與系統開發。</p><p>目前專注於多 Agent 系統、Python 自動化與生成式 AI 整合。希望把研究、開發與驗證串在一起，做出實際可用的產品，也持續探索遊戲與 3D 創作。</p><div className="skills"><span>Multi-Agent Systems</span><span>Workflow Automation</span><span>Data Analytics</span><span>Game Creation</span></div></div></section>
 <section id="contact" className="contact wrap"><div className="contact-inner"><p className="eyebrow">03 / LET’S MAKE SOMETHING</p><h2>下一個點子，<br/>一起<span>沖泡。</span></h2><a href="mailto:leslie0907@gmail.com">leslie0907@gmail.com <ArrowUpRight size={25}/></a></div></section></main><footer className="wrap"><span>© {new Date().getFullYear()} Royal Milktea Master</span><a href="https://github.com/RoyalMilkteaMaster" target="_blank" rel="noreferrer"><Code2 size={16}/> GitHub <ArrowUpRight size={14}/></a><span>BREWED WITH CURIOSITY ✧</span></footer></div>
}




