import assert from 'node:assert/strict';
import {ParticleMorph,galaxy} from './particle-morph.ts';
const start=galaxy(100),target=start.map((v,i)=>i%6<3?v*.4:v*.8),third=galaxy(100,1);
const m=new ParticleMorph(start);m.retarget(target,0,1000);
assert.deepEqual(m.update(0),start);
const middle=m.update(450).slice();m.retarget(third,450,1000);
assert.deepEqual(m.update(450),middle,'Interrupting a transition must not jump');
assert.deepEqual(m.update(1450),third,'Every particle must reach the new target');
assert.deepEqual(m.update(10000),third,'The completed portrait must persist');
assert.throws(()=>m.retarget(new Float32Array(6),0));
assert.ok([...m.current].every(Number.isFinite));
console.log('Particle continuity, interrupted transitions, endpoints and persistent hold passed.');
